### ISSUE TITLE
on user_client side adding functionality

### ISSUE THREAD

**Issue by yeabtsegataye** [REVE-BETA/CustomerSupport#3]
we have to add functionality that perform  when the resolved chat is clicked to fetch the old conversation on the message box without the input filed 
1. on back end
    add API that filter out the message using the selected chat id form the message table (we created relation b/n chat and message 
    table) and only display the message we need 
2. front end 
    we have to fetch the data we get form the API and properly set it in useState and display the message on the message box

**Comment by Betelhem-Belete** [comment]
done
