### ISSUE TITLE
on agent side to add same functionality as the user client side

### ISSUE THREAD

**Issue by yeabtsegataye** [REVE-BETA/CustomerSupport#4]
1. back end 
   add api that filter the resolved message using the selected chat id and form the message table 
2.  front end 
   display the messages without the input filed

**Comment by Betelhem-Belete** [comment]
messages of all the resolved chat will be displayed and the message input text box will be disabled

**Comment by Betelhem-Belete** [comment]
done

**Comment by Betelhem-Belete** [comment]
yeah
