### ISSUE TITLE
adding notification on the agent client side

### ISSUE THREAD

**Issue by yeabtsegataye** [REVE-BETA/CustomerSupport#5]
1. back end
    we add on column on the message table that is "seen" it is Boolean and when the chat is clicked it will be setted to true and when the 
   client send it .. it will be setted false by default so we will show the notification by counting the false one for that specific chat and  
   setting   
    it  
2. front end
    get the data and display it side by side to the chat if we clicked the chat it must be converted to 0 or default form

**Comment by Betelhem-Belete** [comment]
started

**Comment by Betelhem-Belete** [comment]
done
