### ISSUE TITLE
on the client side when the client have open chat and they want to send other message again 

### ISSUE THREAD

**Issue by yeabtsegataye** [REVE-BETA/CustomerSupport#6]
1. back end 
   we have to change the api responsible for warning the client and make it to add new message to the message table withe the created 
   chat id and when the agent accept the request we will update not only the chat receiver but also the message receiver with that chat id 
2. front end 
   nothing match to do hear change will be made on the progress

**Comment by Betelhem-Belete** [comment]
this is also done

**Comment by Betelhem-Belete** [comment]
checked
